/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bms;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SlickBack
 */
public class SalesRecords extends javax.swing.JFrame {

    public String logincode;
    public String base_sal;
    public String bonus;
    public String bonus_code;
    Connection con;
    ResultSet rs;
    PreparedStatement ps;
    public SalesRecords() {
        initComponents();
    }
    public SalesRecords(String ecode){
        initComponents();
        logincode = ecode;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submitSales_btn = new javax.swing.JButton();
        sales_spinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        sales_history = new javax.swing.JTable();
        period_txt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Exit_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        submitSales_btn.setText("Submit");
        submitSales_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitSales_btnActionPerformed(evt);
            }
        });

        sales_history.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Sales", "Bonus", "Base Salary", "Net Salary", "Bonus_code"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sales_history.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sales_historyMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sales_history);

        period_txt.setText("Enter Month");
        period_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                period_txtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Microsoft Uighur", 1, 48)); // NOI18N
        jLabel1.setText("Employee Bonus Details");

        Exit_btn.setText("EXIT");
        Exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_btnActionPerformed(evt);
            }
        });

        refresh_btn.setText("Refresh");
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Exit_btn)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(period_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sales_spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitSales_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(refresh_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Exit_btn)
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(period_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sales_spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitSales_btn)
                    .addComponent(refresh_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void period_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_period_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_period_txtActionPerformed
    public void DBconn(){
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/bms_db","root","");
            ps = con.prepareStatement("select * from bonus_table");
            System.out.println(con);
        }
        catch(ClassNotFoundException ex){
            Logger.getLogger(BMS.class.getName()).log(Level.SEVERE,null,ex);
        }
        catch(SQLException ex){
            Logger.getLogger(BMS.class.getName()).log(Level.SEVERE,null,ex);
        }
    }
    public void tableData(){
        try{
            DBconn();
        DefaultTableModel tbModel = (DefaultTableModel)sales_history.getModel();
            tbModel.setRowCount(0);
            Statement st = con.createStatement();
            String ss ="Select * from bonus_table where e_code = '"+logincode+"'";
            
            rs=ps.executeQuery(ss);
            while (rs.next()){
                String Period = String.valueOf(rs.getString("period"));
                String Base_Sal = String.valueOf(rs.getString("b_sal"));
                String Sales = String.valueOf(rs.getString("sales"));
                String Bonus = String.valueOf(rs.getString("bonus"));
                String Net_Sal = String.valueOf(rs.getString("net_sal"));
                String b_code = String.valueOf(rs.getString("bcode"));
                String tbData[] = {Period,Sales,Bonus,Base_Sal,Net_Sal,b_code};
                tbModel.addRow(tbData);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ManagerApproval.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }
    private void Exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_btnActionPerformed
        close();
        BonusSystem b = new BonusSystem();
        b.setVisible(true);
    }//GEN-LAST:event_Exit_btnActionPerformed

    private void submitSales_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitSales_btnActionPerformed
        
        try {
            int spinn= (Integer)sales_spinner.getValue();
            String spinz = String.valueOf(spinn);
            DBconn();
            ps = con.prepareStatement("update bonus_table set period='"+period_txt.getText()+"',sales='"+spinz+"' where bcode='"+bonus_code+"' and e_code = '"+logincode+"'");
            ps.executeUpdate();
            tableData();

        } catch (SQLException ex) {
            Logger.getLogger(SalesRecords.class.getName()).log(Level.SEVERE, null, ex);
        }
        tableData();
    }//GEN-LAST:event_submitSales_btnActionPerformed

    private void sales_historyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sales_historyMouseClicked
        DefaultTableModel model = (DefaultTableModel)sales_history.getModel();
        int row = sales_history.getSelectedRow();
        base_sal=(model.getValueAt(row,3).toString());
        bonus=(model.getValueAt(row,2).toString());
        bonus_code=(model.getValueAt(row,5).toString());
    }//GEN-LAST:event_sales_historyMouseClicked

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        tableData();
    }//GEN-LAST:event_refresh_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SalesRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SalesRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SalesRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SalesRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SalesRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField period_txt;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JTable sales_history;
    private javax.swing.JSpinner sales_spinner;
    private javax.swing.JButton submitSales_btn;
    // End of variables declaration//GEN-END:variables
}
